- hosts: test
  become: yes
  become_user: root
  tasks:
    - include_vars: var.yml
    - name: Docker login
      shell: 'docker login -u "{{dockerUser}}" -p "{{dockerPasswd}}"'
    - name: Docker pull
      shell: 'docker pull "{{dockerRegis}}":"{{dockerVer}}"'
    - name: Docker run
      shell: 'docker run -d -p 8085:80 "{{dockerRegis}}":"{{dockerVer}}"'



